package utils

import (
	"bytes"
	"context"
	"fmt"
	"github.com/shopspring/decimal"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"
)

type contextKey string

const LangKey contextKey = "lang"
const UserIDKey contextKey = "userID"
const IsAdminKey contextKey = "isAdmin"
const IsStaffKey contextKey = "isStaff"
const ZitadelSubKey contextKey = "zitadelSub"
const TokenExpiryKey contextKey = "tokenExpiry"

// SetLang stores the language in the context.
func SetLang(ctx context.Context, lang string) context.Context {
	return context.WithValue(ctx, LangKey, lang)
}

// GetLang retrieves the language from the context.
func GetLang(ctx context.Context) string {
	lang, _ := ctx.Value(LangKey).(string)
	if lang == "" {
		return "fr"
	}
	return lang
}

func SetUserID(ctx context.Context, userID string) context.Context {
	return context.WithValue(ctx, UserIDKey, userID)
}

func GetUserID(ctx context.Context) string {
	userID, _ := ctx.Value(UserIDKey).(string)
	if userID == "" {
		return ""
	}
	return userID
}

func SetZitadelSub(ctx context.Context, sub string) context.Context {
	return context.WithValue(ctx, ZitadelSubKey, sub)
}

func GetZitadelSub(ctx context.Context) string {
	sub, _ := ctx.Value(ZitadelSubKey).(string)
	return sub
}

func SetIsAdmin(ctx context.Context, isAdmin bool) context.Context {
	return context.WithValue(ctx, IsAdminKey, isAdmin)
}

func GetIsAdmin(ctx context.Context) bool {
	isAdmin, _ := ctx.Value(IsAdminKey).(bool)
	return isAdmin
}

func SetIsStaff(ctx context.Context, isStaff bool) context.Context {
	return context.WithValue(ctx, IsStaffKey, isStaff)
}

// SetTokenExpiry stores the JWT exp claim (UTC) in the context. Zero means
// "no expiry information available" and callers should not enforce a deadline
// on that path.
func SetTokenExpiry(ctx context.Context, exp time.Time) context.Context {
	return context.WithValue(ctx, TokenExpiryKey, exp)
}

// GetTokenExpiry returns the JWT exp stored by the auth middleware, or the
// zero time when none was recorded.
func GetTokenExpiry(ctx context.Context) time.Time {
	exp, _ := ctx.Value(TokenExpiryKey).(time.Time)
	return exp
}

// GetIsStaff returns true when the caller holds the POS staff role OR is an
// admin (admin is a superset of staff).
func GetIsStaff(ctx context.Context) bool {
	if isStaff, _ := ctx.Value(IsStaffKey).(bool); isStaff {
		return true
	}
	return GetIsAdmin(ctx)
}

var slugRegex = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

// validateSlug enforces that a slug is safe to embed in a URL path or a
// multipart field going to the external file service. Slugs generated by
// gosimple/slug already comply, so this is a defense-in-depth check at the
// network boundary — it prevents path traversal or injection if an attacker
// ever influences the stored slug value.
func validateSlug(s string) error {
	if s == "" {
		return fmt.Errorf("slug is empty")
	}
	if len(s) > 128 {
		return fmt.Errorf("slug too long")
	}
	if !slugRegex.MatchString(s) {
		return fmt.Errorf("slug contains invalid characters")
	}
	return nil
}

var (
	alphaRegexp = regexp.MustCompile(`^[A-Za-z]+`)
	numRegexp   = regexp.MustCompile(`\d+`)
)

// ParseCode takes a pointer to a code (e.g., "A10")
// and returns the alphabetical prefix (e.g., "A") and numeric part (10).
func ParseCode(code *string) (string, int) {
	if code == nil {
		// No code? Return empty alpha and 0 for the numeric part
		return "", 0
	}

	alpha := alphaRegexp.FindString(*code)
	numStr := numRegexp.FindString(*code)
	num := 0
	if numStr != "" {
		if n, err := strconv.Atoi(numStr); err == nil {
			num = n
		}
	}
	return alpha, num
}

// FormatDecimal formats a decimal amount using the Belgian French (fr-BE)
// locale convention: comma as decimal separator and a non-breaking space
// as thousands separator. Example: 1234.56 → "1 234,56".
func FormatDecimal(d decimal.Decimal) string {
	fixed := d.StringFixed(2)
	neg := strings.HasPrefix(fixed, "-")
	if neg {
		fixed = fixed[1:]
	}
	parts := strings.SplitN(fixed, ".", 2)
	intPart := parts[0]
	decPart := ""
	if len(parts) == 2 {
		decPart = parts[1]
	}

	// Insert non-breaking space every 3 digits from the right.
	const nbsp = "\u00a0"
	var b strings.Builder
	n := len(intPart)
	for i, r := range intPart {
		if i > 0 && (n-i)%3 == 0 {
			b.WriteString(nbsp)
		}
		b.WriteRune(r)
	}

	out := b.String()
	if decPart != "" {
		out = out + "," + decPart
	}
	if neg {
		out = "-" + out
	}
	return out
}

func UploadProductImage(ctx context.Context, src io.Reader, filename string, imageKey string) error {
	fileSvc := os.Getenv("FILE_SERVICE_URL")
	if fileSvc == "" {
		return fmt.Errorf("FILE_SERVICE_URL env var not set")
	}

	if err := validateSlug(imageKey); err != nil {
		return fmt.Errorf("invalid image key: %w", err)
	}

	var body bytes.Buffer
	writer := multipart.NewWriter(&body)

	// Create the file part
	part, err := writer.CreateFormFile("image", filename)
	if err != nil {
		return fmt.Errorf("create multipart part: %w", err)
	}

	// Copy the file content
	if _, err := io.Copy(part, src); err != nil {
		return fmt.Errorf("copy file bytes: %w", err)
	}

	if err := writer.WriteField("product_slug", imageKey); err != nil {
		return fmt.Errorf("write slug field: %w", err)
	}

	// Close the writer to finalise the multipart body
	if err := writer.Close(); err != nil {
		return fmt.Errorf("close multipart writer: %w", err)
	}

	// Build the request
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, fileSvc+"/upload", &body)
	if err != nil {
		return fmt.Errorf("build upload request: %w", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	// Fire the request
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("upload request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("file service upload failed with status %d", resp.StatusCode)
	}

	return nil
}

// RenameProductImage tells the file service to rename an image from oldSlug to newSlug.
func RenameProductImage(ctx context.Context, oldSlug, newSlug string) error {
	fileSvc := os.Getenv("FILE_SERVICE_URL")
	if fileSvc == "" {
		return fmt.Errorf("FILE_SERVICE_URL env var not set")
	}
	if err := validateSlug(oldSlug); err != nil {
		return fmt.Errorf("invalid old slug: %w", err)
	}
	if err := validateSlug(newSlug); err != nil {
		return fmt.Errorf("invalid new slug: %w", err)
	}

	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	if err := writer.WriteField("old_slug", oldSlug); err != nil {
		return fmt.Errorf("write old_slug field: %w", err)
	}
	if err := writer.WriteField("new_slug", newSlug); err != nil {
		return fmt.Errorf("write new_slug field: %w", err)
	}
	if err := writer.Close(); err != nil {
		return fmt.Errorf("close multipart writer: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, fileSvc+"/rename", &body)
	if err != nil {
		return fmt.Errorf("build rename request: %w", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("rename request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("file service rename failed with status %d", resp.StatusCode)
	}

	return nil
}

// DeleteProductImage tells the file service to delete an image by slug.
func DeleteProductImage(ctx context.Context, slug string) error {
	fileSvc := os.Getenv("FILE_SERVICE_URL")
	if fileSvc == "" {
		return fmt.Errorf("FILE_SERVICE_URL env var not set")
	}
	if err := validateSlug(slug); err != nil {
		return fmt.Errorf("invalid slug: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodDelete, fileSvc+"/delete/"+url.PathEscape(slug), nil)
	if err != nil {
		return fmt.Errorf("build delete request: %w", err)
	}

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("delete request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusNoContent {
		return fmt.Errorf("file service delete failed with status %d", resp.StatusCode)
	}

	return nil
}
