// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
	"tsb-service/internal/modules/order/domain"

	"github.com/99designs/gqlgen/graphql"
	"github.com/google/uuid"
)

type Address struct {
	ID               string   `json:"id"`
	Postcode         string   `json:"postcode"`
	MunicipalityName string   `json:"municipalityName"`
	StreetName       string   `json:"streetName"`
	HouseNumber      string   `json:"houseNumber"`
	BoxNumber        *string  `json:"boxNumber,omitempty"`
	Distance         float64  `json:"distance"`
	Lat              *float64 `json:"lat,omitempty"`
	Lng              *float64 `json:"lng,omitempty"`
	Duration         *int     `json:"duration,omitempty"`
}

type AddressSuggestion struct {
	PlaceID       string `json:"placeId"`
	Description   string `json:"description"`
	MainText      string `json:"mainText"`
	SecondaryText string `json:"secondaryText"`
}

type ChoiceTranslation struct {
	Locale string `json:"locale"`
	Name   string `json:"name"`
}

type ChoiceTranslationInput struct {
	Locale string `json:"locale"`
	Name   string `json:"name"`
}

type Coupon struct {
	ID             uuid.UUID    `json:"id"`
	Code           string       `json:"code"`
	DiscountType   string       `json:"discountType"`
	DiscountValue  string       `json:"discountValue"`
	MinOrderAmount *string      `json:"minOrderAmount,omitempty"`
	MaxUses        *int         `json:"maxUses,omitempty"`
	MaxUsesPerUser *int         `json:"maxUsesPerUser,omitempty"`
	UsedCount      int          `json:"usedCount"`
	IsActive       bool         `json:"isActive"`
	Status         CouponStatus `json:"status"`
	ValidFrom      *time.Time   `json:"validFrom,omitempty"`
	ValidUntil     *time.Time   `json:"validUntil,omitempty"`
	CreatedAt      time.Time    `json:"createdAt"`
}

type CouponValidation struct {
	Valid          bool    `json:"valid"`
	DiscountAmount string  `json:"discountAmount"`
	ErrorMessage   *string `json:"errorMessage,omitempty"`
}

type CreateCouponInput struct {
	Code           string     `json:"code"`
	DiscountType   string     `json:"discountType"`
	DiscountValue  string     `json:"discountValue"`
	MinOrderAmount *string    `json:"minOrderAmount,omitempty"`
	MaxUses        *int       `json:"maxUses,omitempty"`
	MaxUsesPerUser *int       `json:"maxUsesPerUser,omitempty"`
	IsActive       bool       `json:"isActive"`
	ValidFrom      *time.Time `json:"validFrom,omitempty"`
	ValidUntil     *time.Time `json:"validUntil,omitempty"`
}

type CreateOrderInput struct {
	OrderType          OrderTypeEnum           `json:"orderType"`
	IsOnlinePayment    bool                    `json:"isOnlinePayment"`
	AddressPlaceID     *string                 `json:"addressPlaceId,omitempty"`
	AddressExtra       *string                 `json:"addressExtra,omitempty"`
	OrderNote          *string                 `json:"orderNote,omitempty"`
	OrderExtra         []*OrderExtraInput      `json:"orderExtra,omitempty"`
	PreferredReadyTime *time.Time              `json:"preferredReadyTime,omitempty"`
	Items              []*CreateOrderItemInput `json:"items"`
	CouponCode         *string                 `json:"couponCode,omitempty"`
	CashPaymentAmount  *string                 `json:"cashPaymentAmount,omitempty"`
	PaymentRedirectURL *string                 `json:"paymentRedirectUrl,omitempty"`
}

type CreateOrderItemInput struct {
	ProductID  uuid.UUID                        `json:"productId"`
	Quantity   int                              `json:"quantity"`
	ChoiceID   *uuid.UUID                       `json:"choiceId,omitempty"`
	Selections []*CreateOrderItemSelectionInput `json:"selections,omitempty"`
}

type CreateOrderItemSelectionInput struct {
	GroupID  uuid.UUID `json:"groupId"`
	ChoiceID uuid.UUID `json:"choiceId"`
	Quantity int       `json:"quantity"`
}

type CreateProductChoiceGroupInput struct {
	ProductID     uuid.UUID                 `json:"productId"`
	MinSelections int                       `json:"minSelections"`
	MaxSelections int                       `json:"maxSelections"`
	SortOrder     int                       `json:"sortOrder"`
	Translations  []*ChoiceTranslationInput `json:"translations"`
}

type CreateProductChoiceInput struct {
	ProductID     *uuid.UUID                `json:"productId,omitempty"`
	ChoiceGroupID *uuid.UUID                `json:"choiceGroupId,omitempty"`
	PriceModifier string                    `json:"priceModifier"`
	SortOrder     int                       `json:"sortOrder"`
	Translations  []*ChoiceTranslationInput `json:"translations"`
}

type CreateProductInput struct {
	CategoryID       uuid.UUID           `json:"categoryId"`
	Code             *string             `json:"code,omitempty"`
	Image            *graphql.Upload     `json:"image,omitempty"`
	RemoveBackground *bool               `json:"removeBackground,omitempty"`
	IsAvailable      bool                `json:"isAvailable"`
	IsDiscountable   bool                `json:"isDiscountable"`
	IsHalal          bool                `json:"isHalal"`
	IsLunchOnly      bool                `json:"isLunchOnly"`
	IsSpicy          bool                `json:"isSpicy"`
	IsVegetarian     bool                `json:"isVegetarian"`
	IsVisible        bool                `json:"isVisible"`
	PieceCount       *int                `json:"pieceCount,omitempty"`
	Price            string              `json:"price"`
	VatCategory      string              `json:"vatCategory"`
	Translations     []*TranslationInput `json:"translations"`
}

type CustomerStats struct {
	UserID             uuid.UUID     `json:"userId"`
	FirstName          string        `json:"firstName"`
	LastName           string        `json:"lastName"`
	Email              string        `json:"email"`
	PhoneNumber        *string       `json:"phoneNumber,omitempty"`
	RegisteredAt       time.Time     `json:"registeredAt"`
	TotalOrders        int           `json:"totalOrders"`
	TotalAmount        string        `json:"totalAmount"`
	AverageOrderAmount string        `json:"averageOrderAmount"`
	FirstOrderDate     time.Time     `json:"firstOrderDate"`
	LastOrderDate      time.Time     `json:"lastOrderDate"`
	PreferredOrderType OrderTypeEnum `json:"preferredOrderType"`
	DeliveryCount      int           `json:"deliveryCount"`
	PickupCount        int           `json:"pickupCount"`
}

type CustomerStatsInput struct {
	StartDate *time.Time     `json:"startDate,omitempty"`
	EndDate   *time.Time     `json:"endDate,omitempty"`
	OrderType *OrderTypeEnum `json:"orderType,omitempty"`
	MinOrders *int           `json:"minOrders,omitempty"`
}

type CustomerStatsResponse struct {
	Summary   *CustomerStatsSummary `json:"summary"`
	Customers []*CustomerStats      `json:"customers"`
}

type CustomerStatsSummary struct {
	TotalCustomers    int    `json:"totalCustomers"`
	TotalRevenue      string `json:"totalRevenue"`
	AverageOrderValue string `json:"averageOrderValue"`
	TotalOrders       int    `json:"totalOrders"`
}

type DaySchedule struct {
	Open        string  `json:"open"`
	Close       string  `json:"close"`
	DinnerOpen  *string `json:"dinnerOpen,omitempty"`
	DinnerClose *string `json:"dinnerClose,omitempty"`
}

type DayScheduleInput struct {
	Open        string  `json:"open"`
	Close       string  `json:"close"`
	DinnerOpen  *string `json:"dinnerOpen,omitempty"`
	DinnerClose *string `json:"dinnerClose,omitempty"`
}

type Mutation struct {
}

type OpeningHoursInput struct {
	Monday    *DayScheduleInput `json:"monday,omitempty"`
	Tuesday   *DayScheduleInput `json:"tuesday,omitempty"`
	Wednesday *DayScheduleInput `json:"wednesday,omitempty"`
	Thursday  *DayScheduleInput `json:"thursday,omitempty"`
	Friday    *DayScheduleInput `json:"friday,omitempty"`
	Saturday  *DayScheduleInput `json:"saturday,omitempty"`
	Sunday    *DayScheduleInput `json:"sunday,omitempty"`
}

type OrderExtraInput struct {
	Name    string   `json:"name"`
	Options []string `json:"options,omitempty"`
}

type OrderHistoryInput struct {
	StartDate *time.Time          `json:"startDate,omitempty"`
	EndDate   *time.Time          `json:"endDate,omitempty"`
	Status    *domain.OrderStatus `json:"status,omitempty"`
	OrderType *OrderTypeEnum      `json:"orderType,omitempty"`
	Search    *string             `json:"search,omitempty"`
	First     *int                `json:"first,omitempty"`
	Page      *int                `json:"page,omitempty"`
}

type OrderHistoryResponse struct {
	Orders  []*Order             `json:"orders"`
	Summary *OrderHistorySummary `json:"summary"`
}

type OrderHistorySummary struct {
	TotalOrders  int    `json:"totalOrders"`
	TotalRevenue string `json:"totalRevenue"`
	AverageOrder string `json:"averageOrder"`
}

type OrderItem struct {
	Product        *Product              `json:"product"`
	ProductID      uuid.UUID             `json:"productID"`
	UnitPrice      string                `json:"unitPrice"`
	Quantity       int                   `json:"quantity"`
	TotalPrice     string                `json:"totalPrice"`
	VatRateApplied string                `json:"vatRateApplied"`
	ChoiceID       *uuid.UUID            `json:"choiceId,omitempty"`
	Choice         *ProductChoice        `json:"choice,omitempty"`
	Selections     []*OrderItemSelection `json:"selections"`
}

type OrderItemSelection struct {
	GroupID  uuid.UUID           `json:"groupId"`
	ChoiceID uuid.UUID           `json:"choiceId"`
	Quantity int                 `json:"quantity"`
	Group    *ProductChoiceGroup `json:"group"`
	Choice   *ProductChoice      `json:"choice"`
}

type OrderStatusHistory struct {
	ID        uuid.UUID          `json:"id"`
	Status    domain.OrderStatus `json:"status"`
	ChangedAt time.Time          `json:"changedAt"`
}

type Payment struct {
	ID                              uuid.UUID  `json:"id"`
	Resource                        *string    `json:"resource,omitempty"`
	MolliePaymentID                 string     `json:"molliePaymentId"`
	Status                          string     `json:"status"`
	Description                     *string    `json:"description,omitempty"`
	CancelURL                       *string    `json:"cancelUrl,omitempty"`
	WebhookURL                      *string    `json:"webhookUrl,omitempty"`
	CountryCode                     *string    `json:"country_code,omitempty"`
	RestrictPaymentMethodsToCountry *string    `json:"restrictPaymentMethodsToCountry,omitempty"`
	ProfileID                       *string    `json:"profileId,omitempty"`
	SettlementID                    *string    `json:"settlementId,omitempty"`
	OrderID                         uuid.UUID  `json:"orderId"`
	IsCancelable                    bool       `json:"isCancelable"`
	Mode                            *string    `json:"mode,omitempty"`
	Locale                          *string    `json:"locale,omitempty"`
	Method                          *string    `json:"method,omitempty"`
	Metadata                        any        `json:"metadata,omitempty"`
	Links                           any        `json:"links,omitempty"`
	CreatedAt                       time.Time  `json:"createdAt"`
	AuthorizedAt                    *time.Time `json:"authorizedAt,omitempty"`
	PaidAt                          *time.Time `json:"paidAt,omitempty"`
	CanceledAt                      *time.Time `json:"canceledAt,omitempty"`
	ExpiresAt                       *time.Time `json:"expiresAt,omitempty"`
	ExpiredAt                       *time.Time `json:"expiredAt,omitempty"`
	FailedAt                        *time.Time `json:"failedAt,omitempty"`
	Amount                          *float64   `json:"amount,omitempty"`
	AmountRefunded                  *float64   `json:"amountRefunded,omitempty"`
	AmountRemaining                 *float64   `json:"amountRemaining,omitempty"`
	AmountCaptured                  *float64   `json:"amountCaptured,omitempty"`
	AmountChargedBack               *float64   `json:"amountChargedBack,omitempty"`
	SettlementAmount                *float64   `json:"settlementAmount,omitempty"`
}

type Product struct {
	Code           *string               `json:"code,omitempty"`
	CreatedAt      time.Time             `json:"createdAt"`
	ID             uuid.UUID             `json:"id"`
	IsAvailable    bool                  `json:"isAvailable"`
	IsDiscountable bool                  `json:"isDiscountable"`
	IsHalal        bool                  `json:"isHalal"`
	IsLunchOnly    bool                  `json:"isLunchOnly"`
	IsSpicy        bool                  `json:"isSpicy"`
	IsVegetarian   bool                  `json:"isVegetarian"`
	IsVisible      bool                  `json:"isVisible"`
	PieceCount     *int                  `json:"pieceCount,omitempty"`
	Price          string                `json:"price"`
	Slug           string                `json:"slug"`
	VatCategory    string                `json:"vatCategory"`
	Name           string                `json:"name"`
	Description    *string               `json:"description,omitempty"`
	Category       *ProductCategory      `json:"category"`
	Choices        []*ProductChoice      `json:"choices"`
	ChoiceGroups   []*ProductChoiceGroup `json:"choiceGroups"`
	Translations   []*Translation        `json:"translations"`
}

type ProductCategory struct {
	ID           uuid.UUID      `json:"id"`
	Order        int            `json:"order"`
	Name         string         `json:"name"`
	Products     []*Product     `json:"products"`
	Translations []*Translation `json:"translations"`
}

type ProductChoice struct {
	ID            uuid.UUID            `json:"id"`
	ProductID     uuid.UUID            `json:"productId"`
	ChoiceGroupID uuid.UUID            `json:"choiceGroupId"`
	PriceModifier string               `json:"priceModifier"`
	SortOrder     int                  `json:"sortOrder"`
	Name          string               `json:"name"`
	Translations  []*ChoiceTranslation `json:"translations"`
}

type ProductChoiceGroup struct {
	ID            uuid.UUID            `json:"id"`
	ProductID     uuid.UUID            `json:"productId"`
	MinSelections int                  `json:"minSelections"`
	MaxSelections int                  `json:"maxSelections"`
	SortOrder     int                  `json:"sortOrder"`
	Name          string               `json:"name"`
	Translations  []*ChoiceTranslation `json:"translations"`
	Choices       []*ProductChoice     `json:"choices"`
}

type Query struct {
}

type RestaurantConfig struct {
	OrderingEnabled         bool        `json:"orderingEnabled"`
	OpeningHours            any         `json:"openingHours"`
	OrderingHours           any         `json:"orderingHours,omitempty"`
	PreparationMinutes      int         `json:"preparationMinutes"`
	IsCurrentlyOpen         bool        `json:"isCurrentlyOpen"`
	IsOrderingCurrentlyOpen bool        `json:"isOrderingCurrentlyOpen"`
	AvailableSlotsToday     []*TimeSlot `json:"availableSlotsToday"`
	NextOpeningAt           *time.Time  `json:"nextOpeningAt,omitempty"`
	UpdatedAt               time.Time   `json:"updatedAt"`
}

type ScheduleOverride struct {
	Date      time.Time    `json:"date"`
	Closed    bool         `json:"closed"`
	Schedule  *DaySchedule `json:"schedule,omitempty"`
	Note      *string      `json:"note,omitempty"`
	UpdatedAt time.Time    `json:"updatedAt"`
}

type ScheduleOverrideInput struct {
	Date     time.Time         `json:"date"`
	Closed   bool              `json:"closed"`
	Schedule *DayScheduleInput `json:"schedule,omitempty"`
	Note     *string           `json:"note,omitempty"`
}

type Subscription struct {
}

type TimeSlot struct {
	Label              string    `json:"label"`
	Value              time.Time `json:"value"`
	IsLunchOnlyAllowed bool      `json:"isLunchOnlyAllowed"`
}

type Translation struct {
	Description *string `json:"description,omitempty"`
	Language    string  `json:"language"`
	Name        string  `json:"name"`
}

type TranslationInput struct {
	Description *string `json:"description,omitempty"`
	Language    string  `json:"language"`
	Name        string  `json:"name"`
}

type UpdateCouponInput struct {
	Code           *string    `json:"code,omitempty"`
	DiscountType   *string    `json:"discountType,omitempty"`
	DiscountValue  *string    `json:"discountValue,omitempty"`
	MinOrderAmount *string    `json:"minOrderAmount,omitempty"`
	MaxUses        *int       `json:"maxUses,omitempty"`
	MaxUsesPerUser *int       `json:"maxUsesPerUser,omitempty"`
	IsActive       *bool      `json:"isActive,omitempty"`
	ValidFrom      *time.Time `json:"validFrom,omitempty"`
	ValidUntil     *time.Time `json:"validUntil,omitempty"`
}

type UpdateOrderInput struct {
	Status             *domain.OrderStatus             `json:"status,omitempty"`
	EstimatedReadyTime *time.Time                      `json:"estimatedReadyTime,omitempty"`
	CancellationReason *domain.OrderCancellationReason `json:"cancellationReason,omitempty"`
}

type UpdateProductChoiceGroupInput struct {
	MinSelections *int                      `json:"minSelections,omitempty"`
	MaxSelections *int                      `json:"maxSelections,omitempty"`
	SortOrder     *int                      `json:"sortOrder,omitempty"`
	Translations  []*ChoiceTranslationInput `json:"translations,omitempty"`
}

type UpdateProductChoiceInput struct {
	PriceModifier *string                   `json:"priceModifier,omitempty"`
	SortOrder     *int                      `json:"sortOrder,omitempty"`
	Translations  []*ChoiceTranslationInput `json:"translations,omitempty"`
}

type UpdateProductInput struct {
	CategoryID       *uuid.UUID          `json:"categoryID,omitempty"`
	Code             *string             `json:"code,omitempty"`
	Image            *graphql.Upload     `json:"image,omitempty"`
	RemoveBackground *bool               `json:"removeBackground,omitempty"`
	IsAvailable      *bool               `json:"isAvailable,omitempty"`
	IsDiscountable   *bool               `json:"isDiscountable,omitempty"`
	IsHalal          *bool               `json:"isHalal,omitempty"`
	IsLunchOnly      *bool               `json:"isLunchOnly,omitempty"`
	IsSpicy          *bool               `json:"isSpicy,omitempty"`
	IsVegetarian     *bool               `json:"isVegetarian,omitempty"`
	IsVisible        *bool               `json:"isVisible,omitempty"`
	PieceCount       *int                `json:"pieceCount,omitempty"`
	Price            *string             `json:"price,omitempty"`
	VatCategory      *string             `json:"vatCategory,omitempty"`
	Translations     []*TranslationInput `json:"translations,omitempty"`
}

type UpdateUserInput struct {
	FirstName          *string `json:"firstName,omitempty"`
	LastName           *string `json:"lastName,omitempty"`
	Email              *string `json:"email,omitempty"`
	PhoneNumber        *string `json:"phoneNumber,omitempty"`
	AddressPlaceID     *string `json:"addressPlaceId,omitempty"`
	NotifyMarketing    *bool   `json:"notifyMarketing,omitempty"`
	NotifyOrderUpdates *bool   `json:"notifyOrderUpdates,omitempty"`
}

type CouponStatus string

const (
	CouponStatusActive    CouponStatus = "ACTIVE"
	CouponStatusInactive  CouponStatus = "INACTIVE"
	CouponStatusScheduled CouponStatus = "SCHEDULED"
	CouponStatusExpired   CouponStatus = "EXPIRED"
	CouponStatusExhausted CouponStatus = "EXHAUSTED"
)

var AllCouponStatus = []CouponStatus{
	CouponStatusActive,
	CouponStatusInactive,
	CouponStatusScheduled,
	CouponStatusExpired,
	CouponStatusExhausted,
}

func (e CouponStatus) IsValid() bool {
	switch e {
	case CouponStatusActive, CouponStatusInactive, CouponStatusScheduled, CouponStatusExpired, CouponStatusExhausted:
		return true
	}
	return false
}

func (e CouponStatus) String() string {
	return string(e)
}

func (e *CouponStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CouponStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CouponStatus", str)
	}
	return nil
}

func (e CouponStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CouponStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CouponStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderTypeEnum string

const (
	OrderTypeEnumDelivery OrderTypeEnum = "DELIVERY"
	OrderTypeEnumPickup   OrderTypeEnum = "PICKUP"
)

var AllOrderTypeEnum = []OrderTypeEnum{
	OrderTypeEnumDelivery,
	OrderTypeEnumPickup,
}

func (e OrderTypeEnum) IsValid() bool {
	switch e {
	case OrderTypeEnumDelivery, OrderTypeEnumPickup:
		return true
	}
	return false
}

func (e OrderTypeEnum) String() string {
	return string(e)
}

func (e *OrderTypeEnum) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderTypeEnum(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderTypeEnum", str)
	}
	return nil
}

func (e OrderTypeEnum) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderTypeEnum) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderTypeEnum) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
