package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	graphql1 "tsb-service/internal/api/graphql"
	"tsb-service/internal/api/graphql/model"
)

// AutocompleteAddresses is the resolver for the autocompleteAddresses field.
func (r *queryResolver) AutocompleteAddresses(ctx context.Context, input string, sessionToken string) ([]*model.AddressSuggestion, error) {
	suggestions, err := r.AddressService.Autocomplete(ctx, input, sessionToken)
	if err != nil {
		return nil, fmt.Errorf("failed to autocomplete addresses: %w", err)
	}

	gqlSuggestions := make([]*model.AddressSuggestion, len(suggestions))
	for i, s := range suggestions {
		gqlSuggestions[i] = &model.AddressSuggestion{
			PlaceID:       s.PlaceID,
			Description:   s.Description,
			MainText:      s.MainText,
			SecondaryText: s.SecondaryText,
		}
	}

	return gqlSuggestions, nil
}

// ResolveAddress is the resolver for the resolveAddress field.
func (r *queryResolver) ResolveAddress(ctx context.Context, placeID string, sessionToken string) (*model.Address, error) {
	addr, err := r.AddressService.Resolve(ctx, placeID, sessionToken)
	if err != nil {
		return nil, fmt.Errorf("failed to resolve address: %w", err)
	}

	return ToGQLAddress(addr), nil
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
