package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	graphql1 "tsb-service/internal/api/graphql"
	"tsb-service/internal/api/graphql/model"
	assistantApplication "tsb-service/internal/modules/assistant/application"
	assistantDomain "tsb-service/internal/modules/assistant/domain"
)

// StartAssistantLogin is the resolver for the startAssistantLogin field.
func (r *mutationResolver) StartAssistantLogin(ctx context.Context, replaceOwner *bool) (*model.AssistantLogin, error) {
	lg, err := r.AssistantService.StartLogin(ctx, replaceOwner != nil && *replaceOwner)
	if err != nil {
		return nil, assistantError(err)
	}
	return toGQLAssistantLogin(lg), nil
}

// DisconnectAssistant is the resolver for the disconnectAssistant field.
func (r *mutationResolver) DisconnectAssistant(ctx context.Context) (*model.AssistantConnection, error) {
	c, err := r.AssistantService.Disconnect(ctx)
	if err != nil {
		return nil, assistantError(err)
	}
	return toGQLAssistantConnection(c, true), nil
}

// AssistantConnection is the resolver for the assistantConnection field.
func (r *queryResolver) AssistantConnection(ctx context.Context) (*model.AssistantConnection, error) {
	c, err := r.AssistantService.Connection(ctx)
	if errors.Is(err, assistantDomain.ErrDisabled) {
		return toGQLAssistantConnection(c, false), nil
	}
	if err != nil {
		return nil, assistantError(err)
	}
	return toGQLAssistantConnection(c, true), nil
}

// AssistantLogin is the resolver for the assistantLogin field.
func (r *queryResolver) AssistantLogin(ctx context.Context, id string) (*model.AssistantLogin, error) {
	lg, err := r.AssistantService.LoginStatus(ctx, id)
	if err != nil {
		return nil, assistantError(err)
	}
	return toGQLAssistantLogin(lg), nil
}

// AssistantConnectionUpdated is the resolver for the assistantConnectionUpdated field.
func (r *subscriptionResolver) AssistantConnectionUpdated(ctx context.Context) (<-chan *model.AssistantConnection, error) {
	ch := make(chan *model.AssistantConnection, 1)
	sub := r.Broker.Subscribe(assistantApplication.Topic)

	go func() {
		defer close(ch)
		defer r.Broker.Unsubscribe(assistantApplication.Topic, sub)
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-sub:
				if !ok {
					return
				}
				if c, ok := msg.(assistantDomain.Connection); ok {
					select {
					case ch <- toGQLAssistantConnection(c, true):
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
