package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strings"
	graphql1 "tsb-service/internal/api/graphql"
	"tsb-service/internal/api/graphql/model"
	couponDomain "tsb-service/internal/modules/coupon/domain"
	"tsb-service/pkg/utils"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CreateCoupon is the resolver for the createCoupon field.
func (r *mutationResolver) CreateCoupon(ctx context.Context, input model.CreateCouponInput) (*model.Coupon, error) {
	discountValue, err := decimal.NewFromString(input.DiscountValue)
	if err != nil {
		return nil, fmt.Errorf("invalid discount value: %w", err)
	}

	discountType := couponDomain.DiscountType(strings.ToLower(input.DiscountType))
	if err := validateDiscount(discountType, discountValue); err != nil {
		return nil, err
	}

	suppliedCode := ""
	if input.Code != nil {
		suppliedCode = couponDomain.NormalizeCode(*input.Code)
	}

	coupon := &couponDomain.Coupon{
		ID:             uuid.New(),
		Code:           suppliedCode,
		DiscountType:   discountType,
		DiscountValue:  discountValue,
		IsActive:       input.IsActive,
		ValidFrom:      input.ValidFrom,
		ValidUntil:     input.ValidUntil,
		MaxUses:        input.MaxUses,
		MaxUsesPerUser: input.MaxUsesPerUser,
	}

	if input.MinOrderAmount != nil {
		minAmount, err := decimal.NewFromString(*input.MinOrderAmount)
		if err != nil {
			return nil, fmt.Errorf("invalid min order amount: %w", err)
		}
		coupon.MinOrderAmount = &minAmount
	}

	if suppliedCode != "" {
		// Caller chose the code: a collision is a user error.
		if err := r.CouponService.CreateCoupon(ctx, coupon); err != nil {
			if isUniqueViolation(err) {
				return nil, fmt.Errorf("coupon code already exists")
			}
			return nil, fmt.Errorf("failed to create coupon: %w", err)
		}
	} else {
		// No code supplied: generate a unique one, retrying on the rare collision.
		const maxAttempts = 5
		var lastErr error
		for attempt := 0; attempt < maxAttempts; attempt++ {
			code, genErr := couponDomain.GenerateCode()
			if genErr != nil {
				return nil, fmt.Errorf("failed to generate coupon code: %w", genErr)
			}
			coupon.Code = code
			lastErr = r.CouponService.CreateCoupon(ctx, coupon)
			if lastErr == nil {
				break
			}
			if !isUniqueViolation(lastErr) {
				return nil, fmt.Errorf("failed to create coupon: %w", lastErr)
			}
		}
		if lastErr != nil {
			return nil, fmt.Errorf("failed to generate a unique coupon code, please retry")
		}
	}

	gqlCoupon := ToGQLCoupon(coupon)
	r.Broker.Publish("couponUpdated", gqlCoupon)
	return gqlCoupon, nil
}

// UpdateCoupon is the resolver for the updateCoupon field.
func (r *mutationResolver) UpdateCoupon(ctx context.Context, id uuid.UUID, input model.UpdateCouponInput) (*model.Coupon, error) {
	coupon, err := r.CouponService.GetCoupon(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("coupon not found: %w", err)
	}

	if input.Code != nil {
		coupon.Code = couponDomain.NormalizeCode(*input.Code)
	}
	if input.DiscountType != nil {
		coupon.DiscountType = couponDomain.DiscountType(strings.ToLower(*input.DiscountType))
	}
	if input.DiscountValue != nil {
		dv, err := decimal.NewFromString(*input.DiscountValue)
		if err != nil {
			return nil, fmt.Errorf("invalid discount value: %w", err)
		}
		coupon.DiscountValue = dv
	}
	// Validate the final (type, value) pair regardless of which fields were
	// supplied — e.g. switching type from 'fixed' to 'percentage' without
	// resubmitting the value must still be rejected if the value exceeds 100.
	if err := validateDiscount(coupon.DiscountType, coupon.DiscountValue); err != nil {
		return nil, err
	}
	if input.MinOrderAmount != nil {
		minAmount, err := decimal.NewFromString(*input.MinOrderAmount)
		if err != nil {
			return nil, fmt.Errorf("invalid min order amount: %w", err)
		}
		coupon.MinOrderAmount = &minAmount
	}
	if input.MaxUses != nil {
		coupon.MaxUses = input.MaxUses
	}
	if input.MaxUsesPerUser != nil {
		coupon.MaxUsesPerUser = input.MaxUsesPerUser
	}
	if input.IsActive != nil {
		coupon.IsActive = *input.IsActive
	}
	if input.ValidFrom != nil {
		coupon.ValidFrom = input.ValidFrom
	}
	if input.ValidUntil != nil {
		coupon.ValidUntil = input.ValidUntil
	}

	if err := r.CouponService.UpdateCoupon(ctx, coupon); err != nil {
		if isUniqueViolation(err) {
			return nil, fmt.Errorf("coupon code already exists")
		}
		return nil, fmt.Errorf("failed to update coupon: %w", err)
	}

	gqlCoupon := ToGQLCoupon(coupon)
	r.Broker.Publish("couponUpdated", gqlCoupon)
	return gqlCoupon, nil
}

// ValidateCoupon is the resolver for the validateCoupon field.
func (r *queryResolver) ValidateCoupon(ctx context.Context, code string, orderAmount string) (*model.CouponValidation, error) {
	amount, err := decimal.NewFromString(orderAmount)
	if err != nil {
		return nil, fmt.Errorf("invalid order amount: %w", err)
	}

	userID := utils.GetUserID(ctx)
	userUUID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Throttle per-user to block brute-force code enumeration.
	if r.CouponValidateLimiter != nil && !r.CouponValidateLimiter.AllowKey(userID) {
		errMsg := "too many attempts, please try again in a minute"
		return &model.CouponValidation{
			Valid:          false,
			DiscountAmount: "0",
			ErrorMessage:   &errMsg,
		}, nil
	}

	_, discount, err := r.CouponService.ValidateCoupon(ctx, code, amount, userUUID)
	if err != nil {
		// Every error the service returns here carries a user-safe message:
		// the generic invalid-coupon text, the min-order message, or the
		// daily-limit message — so surfacing err.Error() directly is safe.
		errMsg := err.Error()
		return &model.CouponValidation{
			Valid:          false,
			DiscountAmount: "0",
			ErrorMessage:   &errMsg,
		}, nil
	}

	return &model.CouponValidation{
		Valid:          true,
		DiscountAmount: discount.String(),
	}, nil
}

// Coupons is the resolver for the coupons field.
func (r *queryResolver) Coupons(ctx context.Context) ([]*model.Coupon, error) {
	coupons, err := r.CouponService.GetAllCoupons(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get coupons: %w", err)
	}

	result := make([]*model.Coupon, len(coupons))
	for i, c := range coupons {
		result[i] = ToGQLCoupon(c)
	}
	return result, nil
}

// Coupon is the resolver for the coupon field.
func (r *queryResolver) Coupon(ctx context.Context, id uuid.UUID) (*model.Coupon, error) {
	coupon, err := r.CouponService.GetCoupon(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("coupon not found: %w", err)
	}
	return ToGQLCoupon(coupon), nil
}

// CouponUpdated is the resolver for the couponUpdated field.
func (r *subscriptionResolver) CouponUpdated(ctx context.Context) (<-chan *model.Coupon, error) {
	ch := make(chan *model.Coupon, 1)
	sub := r.Broker.Subscribe("couponUpdated")

	go func() {
		defer close(ch)
		defer r.Broker.Unsubscribe("couponUpdated", sub)
		for {
			select {
			case <-ctx.Done():
				return
			case msg, ok := <-sub:
				if !ok {
					return
				}
				if c, ok := msg.(*model.Coupon); ok {
					select {
					case ch <- c:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
