package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"tsb-service/internal/api/graphql/model"

	"github.com/google/uuid"
)

// UpdatePaymentStatus is the resolver for the updatePaymentStatus field.
func (r *mutationResolver) UpdatePaymentStatus(ctx context.Context, orderID uuid.UUID, status string) (*model.Payment, error) {
	// Update the payment status using the service layer
	payment, err := r.PaymentService.UpdatePaymentStatusByOrderID(ctx, orderID, status)
	if err != nil {
		return nil, fmt.Errorf("failed to update payment status: %w", err)
	}

	// Map the domain payment to the GraphQL model
	return ToGQLPayment(payment), nil
}
