package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"tsb-service/internal/api/graphql/model"

	"github.com/google/uuid"
)

// SetUserRrn is the resolver for the setUserRrn field.
func (r *mutationResolver) SetUserRrn(ctx context.Context, userID uuid.UUID, rrn string) (*model.User, error) {
	if err := r.PosService.SetUserRRN(ctx, userID, rrn); err != nil {
		return nil, err
	}
	return r.posHelperFetchUser(ctx, userID)
}

// SetUserPin is the resolver for the setUserPin field.
func (r *mutationResolver) SetUserPin(ctx context.Context, userID uuid.UUID, pin string) (*model.User, error) {
	if err := r.PosService.SetUserPin(ctx, userID, pin); err != nil {
		return nil, err
	}
	return r.posHelperFetchUser(ctx, userID)
}

// RevokePosDevice is the resolver for the revokePosDevice field.
func (r *mutationResolver) RevokePosDevice(ctx context.Context, id uuid.UUID) (*model.PosDevice, error) {
	if err := r.PosService.RevokeDevice(ctx, id); err != nil {
		return nil, err
	}
	devices, err := r.PosService.ListDevices(ctx)
	if err != nil {
		return nil, err
	}
	for i := range devices {
		if devices[i].ID == id {
			return toGQLPosDevice(&devices[i]), nil
		}
	}
	return nil, fmt.Errorf("device not found after revoke")
}

// CreatePosStaff is the resolver for the createPosStaff field.
func (r *mutationResolver) CreatePosStaff(ctx context.Context, displayName string, rrn string, pin string) (*model.PosStaff, error) {
	member, err := r.PosService.CreateStaff(ctx, displayName, rrn, pin)
	if err != nil {
		return nil, err
	}
	return toGQLPosStaff(member), nil
}

// DeletePosStaff is the resolver for the deletePosStaff field.
func (r *mutationResolver) DeletePosStaff(ctx context.Context, id uuid.UUID) (bool, error) {
	if err := r.PosService.DeleteStaff(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// PosDevices is the resolver for the posDevices field.
func (r *queryResolver) PosDevices(ctx context.Context) ([]*model.PosDevice, error) {
	list, err := r.PosService.ListDevices(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PosDevice, 0, len(list))
	for i := range list {
		out = append(out, toGQLPosDevice(&list[i]))
	}
	return out, nil
}

// PosStaff is the resolver for the posStaff field.
func (r *queryResolver) PosStaff(ctx context.Context) ([]*model.PosStaff, error) {
	list, err := r.PosService.ListStaff(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.PosStaff, 0, len(list))
	for i := range list {
		out = append(out, toGQLPosStaff(&list[i]))
	}
	return out, nil
}
