package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
	graphql1 "tsb-service/internal/api/graphql"
	"tsb-service/internal/api/graphql/model"
)

// UpdateOrderingEnabled is the resolver for the updateOrderingEnabled field.
func (r *mutationResolver) UpdateOrderingEnabled(ctx context.Context, enabled bool) (*model.RestaurantConfig, error) {
	config, err := r.RestaurantService.UpdateOrderingEnabled(ctx, enabled)
	if err != nil {
		return nil, fmt.Errorf("update ordering enabled: %w", err)
	}
	return toGQLRestaurantConfig(config.OrderingEnabled, config.OpeningHours, config.UpdatedAt), nil
}

// UpdateOpeningHours is the resolver for the updateOpeningHours field.
func (r *mutationResolver) UpdateOpeningHours(ctx context.Context, hours model.OpeningHoursInput) (*model.RestaurantConfig, error) {
	hoursMap := map[string]any{
		"monday":    toScheduleMap(hours.Monday),
		"tuesday":   toScheduleMap(hours.Tuesday),
		"wednesday": toScheduleMap(hours.Wednesday),
		"thursday":  toScheduleMap(hours.Thursday),
		"friday":    toScheduleMap(hours.Friday),
		"saturday":  toScheduleMap(hours.Saturday),
		"sunday":    toScheduleMap(hours.Sunday),
	}
	hoursJSON, err := json.Marshal(hoursMap)
	if err != nil {
		return nil, fmt.Errorf("marshal opening hours: %w", err)
	}

	config, err := r.RestaurantService.UpdateOpeningHours(ctx, hoursJSON)
	if err != nil {
		return nil, fmt.Errorf("update opening hours: %w", err)
	}
	return toGQLRestaurantConfig(config.OrderingEnabled, config.OpeningHours, config.UpdatedAt), nil
}

// RestaurantConfig is the resolver for the restaurantConfig field.
func (r *queryResolver) RestaurantConfig(ctx context.Context) (*model.RestaurantConfig, error) {
	config, err := r.RestaurantService.GetConfig(ctx)
	if err != nil {
		return nil, fmt.Errorf("get restaurant config: %w", err)
	}
	return toGQLRestaurantConfig(config.OrderingEnabled, config.OpeningHours, config.UpdatedAt), nil
}

// IsCurrentlyOpen is the resolver for the isCurrentlyOpen field.
func (r *restaurantConfigResolver) IsCurrentlyOpen(ctx context.Context, obj *model.RestaurantConfig) (bool, error) {
	if r.RestaurantService.IsDevMode() {
		return true, nil
	}
	config, err := r.RestaurantService.GetConfig(ctx)
	if err != nil {
		return false, fmt.Errorf("get restaurant config: %w", err)
	}
	return config.IsOrderingAllowed(time.Now()), nil
}

// RestaurantConfig returns graphql1.RestaurantConfigResolver implementation.
func (r *Resolver) RestaurantConfig() graphql1.RestaurantConfigResolver {
	return &restaurantConfigResolver{r}
}

type restaurantConfigResolver struct{ *Resolver }
